### PR TITLE
Added `smart_create` tasks method + documentation

### PR DESCRIPTION
**Pull request by kghosesbg**
The smart_create task method automatically finds the file objects from the file names, reducing the amount of boilerplate that one needs to write to set off tasks.

This is because often we run tasks by starting with filenames rather than file objects.

### CODE REVIEW

**Comment by SenadI** [comment]
Hi @kghosesbg,

This smart_create method is something I had in mind for a long time but I would not like to create separate one but rather extend the existing create method to know how to recognize what has been passed in the inputs. This can be done because in app.raw['inputs'] we have the input schema. So when the input schema specifies that the input is a file or an array of files.

-  If input is of type File or File array - use what we have now.
-  If input is of type string we have the following two options.
             1.  If str is a valid ObjectId user passed the ID of the file
             2.        else consider it as a file name
   
This is backwards compatible and extends the call but we need to document it heavily in order to minimize the ambiguity.

Does this makes sense ?

**Comment by kghosesbg** [comment]
Hi @SenadI ,

What you outline is very nice but increases the complexity of the function and introduces at least two external sources of error that a user may find hard to track down.

1. Suppose the CWL spec changes. This means the library MUST also track the CWL spec in order for it to correctly parse app.raw['inputs'] . Right now, the app just has to track the platform API.
2. Suppose someone has a file name that resembles an id? No extension, just a 10 or 12 digit hex-looking string? 

I rather prefer this way, with two separate functions, that does not break existing code, but gives an extra, explicit feature to the user.

Thanks!
-Kaushik

**Comment by SenadI** [comment]
Good point @kghosesbg about CWL spec versions and the file_name ~ file Id. I will think about it a bit more, and will get back with you.

Thanks,

**Comment by SenadI** [comment]
@kghosesbg will not be added. I will leave the sevenbridges-python as an API client only.

**Pull request closed without merging**
