### PR TITLE
Allow revision specification for apps

### LINKED ISSUE #18: Get old app revisions
Retrieving non-current revisions of apps through the API is a challenge because the app IDs attached to the app objects include the number of the latest revision.
This means that when using the `App.get_revision()` function, it tries to append the desired revision number on to the current revision number (resulting in an invalid request).
I'm not quite sure how to fix this, because the instances of App that are retrieved through `api.apps.query()` already come with the revision number attached, but I imagine it would not be too hard for someone who knows the ins and outs of your API wrapper, because the return values of `list-all-apps-available-to-you` do not include revision numbers.

### PR DESCRIPTION
**Pull request by jdagilliland**
This would resolve #18, but seems a bit hackish. Perhaps someone more familiar with the codebase would like to investigate a solution that fits better in to your overall architecture.

### CODE REVIEW

**Comment by SenadI** [comment]
@jdagilliland I've already assumed this might happen. That is why I've placed the `.get_revision` method to be a class method. In that way I meant for it to be used as `api.apps.get_revision()`. But it makes sense that you might ought to have some method for getting App instance revisions.

**Comment by jdagilliland** [comment]
It does make sense to use it as `api.apps.get_revision()`; I'll make sure to switch to that more intuitive invocation in my application, but that wouldn't solve the problem that app IDs coming from `api.apps.query()` will be polluted by already specifying the revision number. Or did you have something else in mind regarding that?

**Comment by SenadI** [comment]
@jdagilliland, no I didn't. Basically it is served in that way (together with the revision) by the server. I will think about it a bit, I can silently strip the revision ( because it is always the latest one ) and the API server interprets no revision as the latest revision. What do you think about that, would this suffice. You will always be able to access the revision on app instance by invoking `app.revision`

**Comment by jdagilliland** [comment]
Yeah, I think that's great, since usually I will want the latest revision anyway, and it sounds like silently stripping the version is a great solution to allow me to get older revisions in the case that I need to.

Note that 1dc9287 only silently strips the ID while calling `.get_revision()`, but not elsewhere; I wasn't sure how to work a more consistent change into the codebase.

**Comment by SenadI** [comment]
@jdagilliland I actually had to do the exactly the same thing just did it as a property. This was the only available option.

**Pull request closed without merging**
